### ISSUE TITLE
add safari support 

### ISSUE THREAD

**Issue by Rahim-444** [justvanrossum/nabla#77] opened 2024-06-12 22:45 UTC
<img width="1680" alt="image" src="https://github.com/justvanrossum/nabla/assets/112757289/57d10807-7d01-43e8-b508-34d83e7dd3fc">

**Comment by justvanrossum** [comment] 2024-06-13 04:53
Duplicate of #59.

For full variability, Nabla doesn’t need to add support for Safari, but Safari needs to add support for COLRv1.

**Closed as completed** 2024-06-23 21:52 UTC
